import { Item } from "@radix-ui/react-dropdown-menu";
import { product } from "./types";
export let products: product[] = [
    {
      title: "Trenton modular sofa_3",
      price: "Rs. 25,000.00",
      id: 1,
      img_url: "/imags/P3.png",
      img1: "/imags/p3.png",
      img2: "/imags/p3.png",
      img3: "/imags/p3.png",
      img4: "/imags/p3.png",
      img5: "/imags/p3.png",
      color: ["#816DAF","#000000","#CDBA7B"],
      size: ["L","Xl","XS"],
      qty: 1,
    },
 
  {
    title: "Granite dining table with dining chair",
    price: "Rs. 25,000.00",
    id: 2,
    img_url: "/imags/P4.png",
    img1: "/imags/P4.png",
    img2: "/imags/P4.png",
    img3: "/imags/P4.png",
    img4: "/imags/P4.png",
    img5: "/imags/P4.png",
    color: ["#816DAF","#000000","#CDBA7B"],
    size: ["L","Xl","XS"],
    qty: 1,
  },
  {
    title: "Outdoor bar table and stool",
    price: "Rs. 25,000.00",
    id: 3,
    img_url: "/imags/P5.png",
    img1: "/imags/P5.png",
    img2: "/imags/P5.png",
    img3: "/imags/P5.png",
    img4: "/imags/P5.png",
    img5: "/imags/P5.png",
    color: ["#816DAF","#000000","#CDBA7B"],
      size: ["L","Xl","XS"],
      qty: 1,
  },
  {
    title: "Plain console with teak mirror",
    price: "Rs. 25,000.00",
    id: 4,
    img_url: "/imags/P6.png",
    img1: "/imags/P6.png",
    img2: "/imags/P6.png",
    img3: "/imags/P6.png",
    img4: "/imags/P6.png",
    img5: "/imags/P6.png",
    color: ["#816DAF","#000000","#CDBA7B"],
      size: ["L","Xl","XS"],
      qty: 1,
  },
  {
    title: "Grain coffee table",
    price: "Rs. 15,000.00",
    id: 5,
    img_url: "/imags/s.5.png",
    img1: "/imags/s.5.png",
    img2: "/imags/s.5.png",
    img3: "/imags/s.5.png",
    img4: "/imags/s.5.png",
    img5: "/imags/s.5.png",
    color: ["#816DAF","#000000","#CDBA7B"],
    size: ["L","Xl","XS"],
    qty: 1,
  },
 
  
  
];